version: '3.1'

services:

  db-service:
    container_name: db-service
    build:
      context: ../db
    restart: always
    env_file:
      - ../db/.env
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 250M
        reservations:
          memory: 250M
    
  spring-boot:
    build: 
        context: ../spring-boot-performance
    depends_on: 
      - db-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 1G
        reservations:
          memory: 1G
          cpus: "4"
    restart: always
